apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: hce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: chaosfy
        image: neosam01/flaskapp:v1
        ports:
        - containerPort: 8989

