apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: hce
spec:
  type: LoadBalancer  # Type of service
  selector:
    app: flaskapp  # Matches the app label from deployment
  ports:
    - protocol: TCP
      port: 8071          # External port (you will access the app on this port)
      targetPort: 8989  # Port that the Flask app is listening on

